## Tensor

텐서는 `NumPy`의 `ndarray`와 유사하지만, GPU나 다른 하드웨어 가속기에서 실행될 수 있다는 점이 다름.

In [2]:
import torch
import numpy as np

### 텐서 생성

In [8]:
# torch.tensor는 input값을 복제하여 Tensor를 만드는 것이므로 
# 입력 값이 무조건 있어야됨
scalar = torch.tensor(7)
scalar, scalar.dtype

(tensor(7), torch.int64)

In [4]:
x_data1 = torch.Tensor()
x_data1

tensor([])

### 텐서 속성

In [9]:
print(f"Shape of scala: {scalar.shape}")
print(f"Datatype of scala: {scalar.dtype}")
print(f"Device scala is stored on:{scalar.device}")
print(f"dimentions: {scalar.ndim}")

Shape of scala: torch.Size([])
Datatype of scala: torch.int64
Device scala is stored on:cpu
dimentions: 0


In [10]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [12]:
vector.ndim

1

In [ ]:
# 1개의 값만 있어야 Scalar로 변환 가능
vector.item()

RuntimeError: a Tensor with 2 elements cannot be converted to Scalar

In [14]:
Matrix = torch.tensor([[7,8],
                       [9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
Matrix.ndim, Matrix.shape

(2, torch.Size([2, 2]))

In [16]:
#Tensor

TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,6]],
                         [[2,3,4],
                          [5,6,7],
                          [8,9,10]]])
print(f"{TENSOR}\n")
print(TENSOR.shape) # <- 3 * 3의 행렬이 2개 존재한다는 것

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  4,  6]],

        [[ 2,  3,  4],
         [ 5,  6,  7],
         [ 8,  9, 10]]])

torch.Size([2, 3, 3])


### 무작위 or 상수 값 사용

- `torch.rand(shape)`: 무작위 값으로 구성된 shape 형태의 텐서
- `torch.ones(shape)`: 1으로 구성된 shape 형태의 텐서 
- `torch.zeros(shape)`: 0으로 구성된 shape 형태의 텐서 

In [4]:
shape = (2,3,)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3800, 0.0175, 0.6036],
        [0.4505, 0.5148, 0.9076]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


- `torch.arange()`
- `torch.empty()`: 초기화 되지 않은 쓰레기 값
- `torch.zeros_like()`: 입력 받은 크기와 같은 크기의 행렬 생성
- `torch.ones_like()`: 

In [17]:
one_to_one = torch.arange(start = 1, end = 11, step = 1)
one_to_one

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
a = torch.empty(size = (2,3))
a, a.shape

(tensor([[-6.2938e+06,  8.5339e-43,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]),
 torch.Size([2, 3]))

In [19]:
b = torch.zeros_like(input = a)
b, b.shape

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 torch.Size([2, 3]))

### 텐서 데이터타입
- 텐서의 **데이터 타입** 이 다르면 error 
- 텐서의 **shape** 이 다르면 error
- 동일한 **장치** 에 존재하지 않으면 error

In [21]:
float_32_tensor = torch.tensor([3., 6., 9. ],
                               dtype = None,
                               device = None,
                               requires_grad = False)
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [22]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [ ]:
# 이 경우엔 형변환이 된 후라서 계산 오류 X 
float_32_tensor + float_16_tensor

tensor([ 6., 12., 18.])

In [24]:
## 자동 형변환, 데이터를 더 잘 표현할 수 있는 타입으로 변경
float_64_tensor = torch.tensor([1.0,2.0,3.0],
                               dtype = torch.float64,
                               device = None,
                               requires_grad = False)

## 명시적으로 형변환 해주는게 좋음
float_64_tensor = float_64_tensor.to(dtype = torch.float16)
float_32_tensor = float_64_tensor.to(dtype = torch.float32)

result = float_64_tensor + float_16_tensor
print(result)
print(float_32_tensor.dtype)

## 큰 신경망에서는 오류가 발생할 수 있음

tensor([ 4.,  8., 12.], dtype=torch.float16)
torch.float32


### 텐서 계산

- `torch.cat()`: 시퀀스를 주어진 차원을 따라 연결
- `torch.tensor.T`: 텐서를 전치(Transpose)
- `torch.matmul()`과 `torch.tensor.mul(torch.tensor)`: 내적

In [26]:
tensor = torch.tensor([1,2,3])
tensor + 100

tensor([101, 102, 103])

In [27]:
tensor * 10

tensor([10, 20, 30])

In [28]:
## 슬라이싱

tensor = torch.ones(4,4) # 텐서 생성

print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[:,-1]}")

tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [29]:
## 텐서 결합 텐서 시퀀스

t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [30]:
print(f"tensor: {tensor}")
print("=" * 30)
print(f"tensor.T: {tensor.T}")
print("=" * 30)

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

print(y1)
print("=" * 30)
print(y2)

tensor: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor.T: tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [31]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [32]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [33]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [34]:
x = x.type(dtype = torch.float32)
torch.mean(x)

tensor(45.)

In [35]:
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [36]:
torch.sum(x), x.sum()

(tensor(450.), tensor(450.))

### PyTorch와 NumPy 상호 변환
- `torch.tensor.numpy()`: 텐서를 NumPy 배열로 변환
- `torch.from_numpy(ndarray)`: NumPy 배열을 텐서로 변환

In [14]:
t = torch.ones(5)
print(f"t: {t}")

n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [17]:
n = np.ones(5)
t = torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)